app = "keycloak-bazafirm"
primary_region = 'fra'

[metrics]
  path = "/metrics"
  port = 9000

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[http_service]
  internal_port = 9000
  force_https = true
  auto_start_machines = true